{{- if .Values.zabbixAgent.rbac.create -}}
{{- if .Values.zabbixAgent.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "zabbix.agent.serviceAccountName" . }}
  labels:
    app: {{ template "zabbix.name" . }}
    chart: {{ template "zabbix.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
{{ toYaml .Values.zabbixAgent.serviceAccount.annotations | indent 4 }}
imagePullSecrets:
{{ toYaml .Values.zabbixAgent.serviceAccount.imagePullSecrets | indent 2 }}
{{- end -}}
{{- end -}}