port=0
log-dhcp

dhcp-no-override
dhcp-range=10.0.0.94,proxy
dhcp-boot=,,10.0.0.94

dhcp-match=set:ipxe-http,175,19
dhcp-match=set:ipxe-https,175,20
dhcp-match=set:ipxe-menu,175,39
# pcbios specific
dhcp-match=set:ipxe-pxe,175,33
dhcp-match=set:ipxe,175,24
dhcp-match=set:ipxe-iscsi,175,17
# efi specific
dhcp-match=set:ipxe-efi,175,36
# combination
# set ipxe-ok tag if we have correct combination
# http && menu && iscsi ((pxe && bzimage) || efi)
tag-if=set:ipxe-ok,tag:ipxe-http,tag:ipxe-menu,tag:ipxe-iscsi,tag:ipxe-pxe,tag:ipxe-bzimage
tag-if=set:ipxe-ok,tag:ipxe-http,tag:ipxe-menu,tag:ipxe-iscsi,tag:ipxe-efi

#pxe-service=[tag:<tag>,]<CSA>,<menu text>[,<basename>|<bootservicetype>][,<server address>|<server_name>]
#pxe-prompt=[tag:<tag>,]<prompt>[,<timeout>]
# these create option 43 cruft, which is required in proxy mode
# TFTP IP is required on all dhcp-boot lines (unless dnsmasq itself acts as tftp server?)
pxe-service=tag:!ipxe-ok,X86PC,PXE,undionly.kpxe
pxe-service=tag:!ipxe-ok,IA32_EFI,PXE,snponlyx32.efi
pxe-service=tag:!ipxe-ok,BC_EFI,PXE,snponly.efi
pxe-service=tag:!ipxe-ok,X86-64_EFI,PXE,ipxe.efi


# later match overrides previous, keep ipxe script last
# server address must be non zero, but can be anything as long as iPXE script is not fetched over TFTP
#dhcp-boot=tag:ipxe-ok,http://boot.ipxe.org/demo/boot.php,,0.0.0.1
dhcp-boot=tag:!ipxe,ipxe.efi
dhcp-boot=tag:ipxe-efi,https://10.0.0.94:9443/pxeboot/ipxe-boot-efi

enable-tftp
tftp-root=//pxeboot

dhcp-leasefile=/tmp/dnsmasq.leases



all-servers
bind-interfaces
listen-address =10.0.3.1,127.0.1.1,10.0.5.1,::1,10.0.7.1
log-facility=/var/log/network/dnsmasq.log
pid-file=/var/run/network/dnsmasq.pid
port=53
resolv-file=/etc/resolv.dnsmasq
user=admin
