apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allowlocalnamespace
spec:
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ namespace }}
  podSelector: {}
  policyTypes:
  - Egress
